### PR TITLE
[16.0][ADD] Add real estate base addons

### PR DESCRIPTION
**Pull request by ronny-montano**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@curonny Thanks for this.

Have you see there are already implemented addons there https://github.com/OCA/vertical-realestate/tree/13.0/realestate_estate ?

**Comment by jelenapoblet** [comment]
@rousseldenis In this case, we've developed a more feature-rich real estate repository, including website integration for online apartment showcasing. Can this repo be considered instead of the other one?"

**Comment by rousseldenis** [comment]
> @rousseldenis In this case, we've developed a more feature-rich real estate repository, including website integration for online apartment showcasing. Can this repo be considered instead of the other one?"

What do you call the other one ? Which one ?

Why not include website integration in a separate module on top of existing ones?

**Comment by rousseldenis** [comment]
@curonny FYI I will migrate soon the 13.0 ones to 16.0

**Comment by jelenapoblet** [comment]
@rousseldenis Our approach extends the product model to add the property and enhances all website features.
When i ment "the other one" i mean, if it's possible, replace the existing repo for this one, since the approach is different.
If not, what would you recommend to do ?

**Comment by rousseldenis** [comment]
Mmmh The problem with your approach is all the fields that are estate properties are on the product level... That seems weird and can conduct to conflicts

**Comment by jelenapoblet** [comment]
We understand the concern about estate properties being on the product level, but this method allows us to avoid rewriting website code, saving time and resources ... we'd be happy to discuss further if you're open to it, how would you propose addressing these challenges?

**Comment by rousseldenis** [comment]
> We understand the concern about estate properties being on the product level, but this method allows us to avoid rewriting website code, saving time and resources ... we'd be happy to discuss further if you're open to it, how would you propose addressing these challenges?

The fastest way should be renaming the module to identify the specific way you did it

**Comment by ronny-montano** [comment]
@rousseldenis  first step done.. next step?

**Comment by jelenapoblet** [comment]
@BinhexTeam check this please.

**Pull request closed without merging**
