### PR TITLE
[13.0][ADD] First modules

### PR DESCRIPTION
**Pull request by rousseldenis**
* [x] realestate: Base module for security, abstract model, ...
* [x] realestate_estate
* [x] realsestate_image

### CODE REVIEW

**Comment by dreispt** [comment]
Reviewers stay far from big diffs.
If you can split your code in several PRS, it will be easier to review.
Try creating one for each module being contributed.

**Comment by rousseldenis** [comment]
> Reviewers stay far from big diffs.
> If you can split your code in several PRS, it will be easier to review.
> Try creating one for each module being contributed.

Indeed, I know. I splitted the commits, so it should not be so difficult to review by commit. Did that as code is quite old. Further modules/features should be done in the good way. If you prefer I can split for sure. Alphas modules

**Comment by dreispt** [comment]
I can do per commit reviews.

**Comment by dreispt** [comment]
Don't forget to make Mr Travis happy.

**Comment by rousseldenis** [comment]
@dreispt This one is ready. Got troubles with pre-commit but aligned on v14 version.

**Pull request closed without merging**
